"""Generate a deterministic, compact repository snapshot for AI orientation."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
import tomllib


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "generated" / "REPOSITORY_SNAPSHOT.md"
CORE = ROOT / "collie-core"
DESKTOP = ROOT / "collie-ui"


def relative(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def count_files(base: Path, patterns: tuple[str, ...]) -> int:
    ignored_parts = {
        ".git",
        ".venv",
        "node_modules",
        "dist",
        "out",
        "build",
        "__pycache__",
        ".pytest_cache",
        ".tmp-pytest-audit",
        ".ruff_cache",
        ".vinext",
        ".wrangler",
    }
    found: set[Path] = set()
    if not base.exists():
        return 0
    for pattern in patterns:
        for path in base.rglob(pattern):
            if path.is_file() and not ignored_parts.intersection(path.parts):
                found.add(path)
    return len(found)


def python_version() -> str:
    config = CORE / "pyproject.toml"
    if not config.exists():
        return "missing"
    with config.open("rb") as handle:
        return str(tomllib.load(handle).get("project", {}).get("version", "unknown"))


def package_version(base: Path) -> str:
    config = base / "package.json"
    if not config.exists():
        return "missing"
    return str(json.loads(config.read_text(encoding="utf-8")).get("version", "unknown"))


def child_directories(base: Path) -> list[str]:
    if not base.exists():
        return []
    ignored = {"__pycache__", ".pytest_cache", ".ruff_cache"}
    return sorted(path.name for path in base.iterdir() if path.is_dir() and path.name not in ignored)


def render() -> str:
    core_modules = child_directories(CORE / "collie_core")
    sections = [
        "# Repository snapshot",
        "",
        "> Generated by `collie-core/.venv/Scripts/python.exe tools/update_project_snapshot.py`. Do not edit by hand.",
        "",
        "## Component locations",
        "",
        "| Component | Path | Version |",
        "| --- | --- | --- |",
        f"| Python core | `{relative(CORE)}/` | `{python_version()}` |",
        f"| Electron desktop | `{relative(DESKTOP)}/` | `{package_version(DESKTOP)}` |",
        "",
        "## Source inventory",
        "",
        f"- Core Python files: **{count_files(CORE, ('*.py',))}**",
        f"- Core Python test files: **{count_files(CORE / 'tests', ('test_*.py',))}**",
        f"- Desktop TypeScript/TSX files: **{count_files(DESKTOP / 'src', ('*.ts', '*.tsx'))}**",
        f"- Desktop test files: **{count_files(DESKTOP, ('*.test.ts', '*.test.tsx'))}**",
        f"- Active Markdown docs: **{count_files(ROOT / 'docs', ('*.md',)) - count_files(ROOT / 'docs' / 'archive', ('*.md',)) - count_files(ROOT / 'docs' / 'generated', ('*.md',))}**",
        f"- Archived Markdown docs: **{count_files(ROOT / 'docs' / 'archive', ('*.md',))}**",
        "",
        "## Collie-owned core module groups",
        "",
        ", ".join(f"`{name}`" for name in core_modules) if core_modules else "Core source not found.",
        "",
        "## Required orientation files",
        "",
        "- `AGENTS.md`",
        "- `docs/VISION.md`",
        "- `docs/PROJECT_MAP.md`",
        "- `docs/WORKFLOW.md`",
        f"- `{relative(CORE)}/AGENTS.md`",
        f"- `{relative(DESKTOP)}/AGENTS.md`",
        "",
    ]
    return "\n".join(sections)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated snapshot is missing or stale.",
    )
    args = parser.parse_args()
    expected = render()

    required = [
        ROOT / "AGENTS.md",
        ROOT / "docs" / "VISION.md",
        ROOT / "docs" / "PROJECT_MAP.md",
        ROOT / "docs" / "WORKFLOW.md",
        CORE / "AGENTS.md",
        DESKTOP / "AGENTS.md",
    ]
    missing = [relative(path) for path in required if not path.exists()]
    if missing:
        print("Missing required orientation files: " + ", ".join(missing), file=sys.stderr)
        return 1

    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print("Repository snapshot is stale; run tools/update_project_snapshot.py", file=sys.stderr)
            return 1
        print("Repository snapshot is current.")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Updated {relative(OUTPUT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
